name: ci

on:
  push:
    branches:
      - "beihai"

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: apply to all-in-one environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AIO_ALBANY_HOST }}
          username: ${{ secrets.AIO_ALBANY_USERNAME }}
          key: ${{ secrets.AIO_ALBANY_KEY }}
          port: ${{ secrets.AIO_ALBANY_PORT }}
          script: |
            set -ex
            rm -rf openv2x-aio-beihai.tar.gz && wget https://openv2x.oss-ap-southeast-1.aliyuncs.com/deploy/beihai/openv2x-aio-beihai.tar.gz
            rm -rf src && tar zxvf openv2x-aio-beihai.tar.gz
            cd src
            . ~/.bashrc
            env | grep OPENV2X | grep -v -i pass > /tmp/env.txt
            bash install.sh
